server:
  port: 7005
spring:
  application:
    name: cloud-user-center-provider-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'