server:
  port: 10010

spring:
  application:
    name: dn-nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.79.120:8848
      username: nacos
      password: nacos

# spring boot actuator
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always